version: '3.3'

services:
  app:
    build: "."
    depends_on:
      - postgres
    ports:
      - 5000:5000
  rtmp:
    image: alfg/nginx-rtmp
    ports:
      - 1935:1935
      - 8080:80
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
