version: '3.3'

services:
  # app:
  #   build: '.'
  #   depends_on:
  #     - app-postgres
  #   ports:
  #     - 5000:5000
  # rtmp:
  #   image: alfg/nginx-rtmp
  #   ports:
  #     - 1935:1935
  #     - 8080:80
  # app-postgres:
  #   image: postgres:9.6
  #   ports:
  #     - '5433:5432'
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  chat-service-scylla:
    image: scylladb/scylla
    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 9160:9160
      - 10000:10000
  kratos-migrate:
    image: oryd/kratos:v0.10.1
    environment:
      - DSN=postgres://${KRATOS_POSTGRES_USER}:${KRATOS_POSTGRES_PASSWORD}@kratos-postgres:5432/${KRATOS_POSTGRES_DB}?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: .docker/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.10.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://${KRATOS_POSTGRES_USER}:${KRATOS_POSTGRES_PASSWORD}@kratos-postgres:5432/${KRATOS_POSTGRES_DB}?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
      - SECRETS_COOKIE_0=${KRATOS_COOKIE_SECRET}
      - SECRETS_CIPHER_0=${KRATOS_CIPHER_SECRET}
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: .docker/kratos
        target: /etc/config/kratos
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
  kratos-postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${KRATOS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${KRATOS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${KRATOS_POSTGRES_DB}
